# Generated by Django 4.0.4 on 2022-04-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
