# Generated by Django 4.0.4 on 2022-04-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0002_alter_medicamento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='no_disponible',
        ),
    ]
