# Generated by Django 4.0.4 on 2022-04-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0003_remove_medicamento_no_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
