# Generated by Django 4.0.4 on 2022-04-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0004_alter_medicamento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
