# Generated by Django 4.0.4 on 2022-04-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0005_alter_medicamento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='imagen',
        ),
    ]
