# Generated by Django 4.0.4 on 2022-04-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0006_remove_medicamento_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='id',
            new_name='id_medicamento',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
