# Generated by Django 4.0.4 on 2022-04-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0007_rename_id_medicamento_id_medicamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='id_medicamento',
            new_name='idMed',
        ),
    ]
