# Generated by Django 4.0.4 on 2022-05-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0008_rename_id_medicamento_medicamento_idmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='imagen',
        ),
    ]
