# Generated by Django 4.0.4 on 2022-05-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0009_remove_medicamento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='precio',
        ),
    ]
