# Generated by Django 4.0.4 on 2022-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0010_remove_medicamento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='disponible',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='miligramos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
