# Generated by Django 4.0.4 on 2022-05-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0011_alter_medicamento_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='idMed',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombreMed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
