# Generated by Django 4.0.4 on 2022-05-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0013_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
