# Generated by Django 4.0.4 on 2022-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0014_delete_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPac', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('idFicha', models.IntegerField(blank=True)),
                ('idDr', models.IntegerField(blank=True)),
                ('diagnostico', models.CharField(blank=True, max_length=100)),
                ('prescripcion', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
