# Generated by Django 4.0.4 on 2022-05-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAPI', '0015_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idPac', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('rutPac', models.CharField(blank=True, max_length=100)),
                ('nombrePac', models.CharField(blank=True, max_length=100)),
                ('idFicha', models.IntegerField(blank=True)),
                ('idDr', models.IntegerField(blank=True)),
                ('diagnostico', models.CharField(blank=True, max_length=100)),
                ('prescripcion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
